- name: "Remove and unconfigure any other DMs that may be installed"
  ansible.builtin.include_tasks: remove_other_dms/main.yml
  when: remove_other_display_managers

- name: "Install Ly packages"
  ansible.builtin.include_tasks: install/main.yml

- name: "Set Ly to startup at boot"
  ansible.builtin.include_tasks: startup/main.yml

- name: "Configure Ly settings"
  ansible.builtin.include_tasks: config/main.yml

