- name: "Disable other DM services from starting at boot: {{ services_to_disable }}"
  ansible.builtin.service:
    name: "{{ service_name }}"
    enabled: no
  failed_when: false
  loop: "{{ services_to_disable }}"
  loop_control:
    loop_var: 'service_name'
  vars:
    services_to_disable:
      - lightdm
  become: true
  become_user: root

- name: "Uninstall other DM packages: {{ packages_to_uninstall }}"
  ansible.builtin.package:
    name: "{{ packages_to_uninstall }}"
    state: absent
  vars:
    packages_to_uninstall:
      - lightdm
      - lightdm-gtk-greeter
  become: true
  become_user: root

