- name: "Configure common Ly settings for Linux"
  ansible.builtin.include_tasks: common_config.yml
  vars:
    ly_config_path: "{{ linux_ly_config_path }}"
    xorg_server_cmd: "{{ linux_xorg_server_cmd }}"
    xorg_xauth_cmd: "{{ linux_xorg_xauth_cmd }}"
    xsessions_dir: "{{ linux_xsessions_dir }}"
  when: ansible_system == "Linux"

- name: "Configure common Ly settings for FreeBSD"
  ansible.builtin.include_tasks: common_config.yml
  vars:
    ly_config_path: "{{ freebsd_ly_config_path }}"
    xorg_server_cmd: "{{ freebsd_xorg_server_cmd }}"
    xorg_xauth_cmd: "{{ freebsd_xorg_xauth_cmd }}"
    xsessions_dir: "{{ freebsd_xsessions_dir }}"
  when: ansible_os_family == "FreeBSD"

- name: "Configure OS-specific settings for FreeBSD"
  ansible.builtin.include_tasks: freebsd/main.yml
  when: ansible_os_family == "FreeBSD"

