- name: "Configure common Ly settings for Linux"
  ansible.builtin.include_tasks: common_config.yml
  vars:
    ly_config_path: "{{ linux_ly_config_path }}"
    path_env_var: "{{ linux_path_env_var }}"
    login_save_path: "{{ linux_login_save_path }}"
    cookie_gen_cmd: "{{ linux_cookie_gen_cmd }}"
    xorg_server_cmd: "{{ linux_xorg_server_cmd }}"
    xorg_xauth_cmd: "{{ linux_xorg_xauth_cmd }}"
    xsessions_dir: "{{ linux_xsessions_dir }}"
    ly_xsetup_script: "{{ linux_ly_xsetup_script }}"
    wayland_sessions_dir: "{{ linux_wayland_sessions_dir }}"
    ly_wayland_setup_script: "{{ linux_ly_wayland_setup_script }}"
  when: ansible_system == "Linux"

- name: "Configure common Ly settings for FreeBSD"
  ansible.builtin.include_tasks: common_config.yml
  vars:
    ly_config_path: "{{ freebsd_ly_config_path }}"
    path_env_var: "{{ freebsd_path_env_var }}"
    login_save_path: "{{ freebsd_login_save_path }}"
    cookie_gen_cmd: "{{ freebsd_cookie_gen_cmd }}"
    xorg_server_cmd: "{{ freebsd_xorg_server_cmd }}"
    xorg_xauth_cmd: "{{ freebsd_xorg_xauth_cmd }}"
    xsessions_dir: "{{ freebsd_xsessions_dir }}"
    ly_xsetup_script: "{{ freebsd_ly_xsetup_script }}"
    wayland_sessions_dir: "{{ freebsd_wayland_sessions_dir }}"
    ly_wayland_setup_script: "{{ freebsd_ly_wayland_setup_script }}"
  when: ansible_os_family == "FreeBSD"

- name: "Configure OS-specific settings for FreeBSD"
  ansible.builtin.include_tasks: freebsd/main.yml
  when: ansible_os_family == "FreeBSD"

