- name: "Set terminal configuration for Ly in '{{ freebsd_terminal_config_path }}'"
  ansible.builtin.blockinfile:
    path: "{{ freebsd_terminal_config_path }}"
    block: |
      Ly:\
          :lo=/usr/local/bin/ly:\
          :al=root:
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Ly display manager terminal config"
    state: present
    create: false
  become: true
  become_user: root

- name: "Comment out default virtual console {{ virtual_console_num }} config in '{{ freebsd_console_config_path }}'"
  ansible.builtin.lineinfile:
    path: "{{ freebsd_console_config_path }}"
    regexp: >-
      ^(# )?ttyv{{ virtual_console_num }}(.*)$
    line: >-
      # ttyv{{ virtual_console_num }}\2
    state: present
    firstmatch: true
    create: false
    backrefs: true
    backup: true
  become: true
  become_user: root

- name: "Set virtual console {{ virtual_console_num }} config for Ly in '{{ freebsd_console_config_path }}'"
  ansible.builtin.blockinfile:
    path: "{{ freebsd_console_config_path }}"
    block: |
      ttyv{{ virtual_console_num }} "/usr/libexec/getty Ly" xterm on secure
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Ly virtual console config"
    state: present
    create: false
  become: true
  become_user: root

